import { useState } from 'react';
import { Link } from 'react-router-dom';
import { X } from 'lucide-react';
import { AnalystLayout } from '../../components/analyst/AnalystLayout';
import { FieldLabel, inputCls } from '../../components/shared/Modal';
import { useApp } from '../../store/AppStore';
import { downloadFile, escapeHtml, fmtDate, fmtDateTime, nowISO, addDays } from '../../lib/format';
import type { GeneratedReport } from '../../types';

function reportHtml(r: GeneratedReport) {
  return `<!doctype html><html><head><meta charset="utf-8"><title>${escapeHtml(r.title)}</title>
<style>body{font-family:Inter,Arial,sans-serif;color:#1A1A2E;max-width:800px;margin:40px auto;padding:0 20px}h1{color:#104E49}.muted{color:#6B7280;font-size:13px}li{margin-bottom:8px}</style></head>
<body><div class="muted">RWANDA BIOMEDICAL CENTRE · HEALTH ANALYTICS</div><h1>${escapeHtml(r.title)}</h1>
<p class="muted">Prepared by ${escapeHtml(r.author)} · ${fmtDate(r.at)}</p>
<h2>Findings</h2><ol>${r.summary.highlights.map((h) => `<li>${escapeHtml(h)}</li>`).join('')}</ol>
<p class="muted">Generated by the AI Vital frontend prototype. Figures are demonstration data.</p></body></html>`;
}

export function AnalystReports() {
  const { state, actions } = useApp();
  const [title, setTitle] = useState('Health Analytics Brief — Week 23');
  const findings = state.analystFindings;
  const reports = state.reports.filter((r) => r.type === 'analyst');

  const create = () => {
    const r = actions.addReport({
      title: title.trim() || 'Health Analytics Brief',
      type: 'analyst',
      format: 'HTML',
      language: 'English',
      periodFrom: addDays(nowISO(), -7).slice(0, 10),
      periodTo: nowISO().slice(0, 10),
      district: 'National',
      sections: Array.from(new Set(findings.map((f) => f.source))),
      status: 'Draft',
      ok: true,
      summary: {
        alertsTotal: 0,
        alertsBySeverity: { red: 0, orange: 0, yellow: 0, green: 0 },
        alertsOpen: 0,
        alertsAcknowledged: 0,
        alertsResolved: 0,
        interventionsTotal: 0,
        interventionsCompleted: 0,
        investigationsActive: 0,
        topDiseases: [],
        highlights: findings.map((f) => `[${f.source}] ${f.title} — ${f.detail}`)
      }
    });
    actions.clearFindings();
    actions.toast(`${r.title} created with ${r.summary.highlights.length} finding(s).`);
  };

  return (
    <AnalystLayout
      title="Analysis Reports"
      subtitle="Generate and manage public health analysis reports"
      breadcrumb="Analysis Reports">

      <div className="grid grid-cols-1 lg:grid-cols-[minmax(0,1fr)_380px] gap-6">
        <div className="bg-white rounded-lg shadow-card border border-border p-6">
          <h2 className="text-[16px] font-bold text-epi-text mb-1">Report draft</h2>
          <p className="text-[13px] text-epi-muted mb-5">
            Use “Add to Report” on Correlation, Explore, Scenarios and Vulnerable Populations to collect findings here.
          </p>
          {findings.length === 0 ?
          <div className="flex flex-col items-center justify-center text-center py-12">
              <div className="w-16 h-16 bg-epi/10 rounded-full flex items-center justify-center mb-4">
                <span className="text-[24px]">📄</span>
              </div>
              <p className="text-[14px] text-epi-muted max-w-md mb-4">No findings collected yet.</p>
              <div className="flex flex-wrap gap-2 justify-center">
                <Link to="/analyst/correlation" className="h-9 px-4 inline-flex items-center border border-border rounded-md text-[13px] font-bold text-epi hover:bg-epi-bg">Correlation</Link>
                <Link to="/analyst/explore" className="h-9 px-4 inline-flex items-center border border-border rounded-md text-[13px] font-bold text-epi hover:bg-epi-bg">Explore Data</Link>
                <Link to="/analyst/scenarios" className="h-9 px-4 inline-flex items-center border border-border rounded-md text-[13px] font-bold text-epi hover:bg-epi-bg">Scenarios</Link>
              </div>
            </div> :

          <>
              <ul className="space-y-3 mb-6">
                {findings.map((f) =>
              <li key={f.id} className="border border-border rounded-md p-3 flex gap-3">
                    <div className="flex-1 min-w-0">
                      <div className="text-[11px] font-bold text-epi uppercase">{f.source} · {fmtDateTime(f.at)}</div>
                      <div className="text-[13px] font-bold text-epi-text">{f.title}</div>
                      <div className="text-[12px] text-epi-muted mt-1">{f.detail}</div>
                    </div>
                    <button aria-label="Remove finding" onClick={() => actions.removeFinding(f.id)} className="text-epi-muted hover:text-epi-red self-start">
                      <X className="w-4 h-4" />
                    </button>
                  </li>
              )}
              </ul>
              <FieldLabel>Report title</FieldLabel>
              <input value={title} onChange={(e) => setTitle(e.target.value)} className={inputCls} />
              <button onClick={create} className="mt-4 h-10 px-6 bg-epi hover:bg-epi-hover text-white text-[14px] font-bold rounded-md">
                Create New Report ({findings.length} finding{findings.length === 1 ? '' : 's'})
              </button>
            </>
          }
        </div>

        <div className="bg-white rounded-lg shadow-card border border-border p-6">
          <h2 className="text-[16px] font-bold text-epi-text mb-4">Generated reports</h2>
          {reports.length === 0 ?
          <p className="text-[13px] text-epi-muted">No analysis reports generated in this session.</p> :

          <ul className="divide-y divide-border">
              {reports.map((r) =>
            <li key={r.id} className="py-3">
                  <div className="text-[13px] font-bold text-epi-text">{r.title}</div>
                  <div className="text-[12px] text-epi-muted">{r.id} · {fmtDateTime(r.at)} · {r.summary.highlights.length} findings · {r.status}</div>
                  <div className="flex gap-3 mt-2">
                    <button
                  onClick={() => downloadFile(`${r.title.replace(/[^a-z0-9]+/gi, '-').toLowerCase()}.html`, reportHtml(r), 'text/html')}
                  className="text-[12px] font-bold text-epi hover:underline">
                      Download
                    </button>
                    {r.status === 'Draft' &&
                <button
                  onClick={() => {
                    actions.updateReport(r.id, { status: 'Shared with Epidemiology' });
                    actions.sendNotification(
                      { title: 'New analysis report', body: `${r.title} shared by ${r.author}.`, severity: 'info', roles: ['epi'] },
                      { module: 'Analytics', action: 'Shared analysis report' }
                    );
                    actions.toast('Report shared with the Epidemiology team.');
                  }}
                  className="text-[12px] font-bold text-epi hover:underline">
                        Share with Epi team
                      </button>
                }
                  </div>
                </li>
            )}
            </ul>
          }
        </div>
      </div>
    </AnalystLayout>);

}
